---
- hosts: all
  gather_facts: true
  tasks:
  - debug: var=ansible_facts
#  - debug: var=eth1

- hosts: server
  become: yes
  become_method: sudo
  vars:
    consul:
      version: 1.3.0
      server: true
    nomad:
      version: 0.8.3
      server: true
      client: true
  roles:
    - role: docker
    - role: consul
    - role: nomad

- hosts: client-*
  become: yes
  become_method: sudo
  vars:
    consul:
      version: 1.3.0
    nomad:
      version: 0.8.3
      client: true
      server: false
  roles:
    - role: docker
    - role: consul
    - role: nomad
